# Restaurant -> Season / Episode / Name / Location

# What should a restaurant look like?
# Restaurant {
#   name: "Bilbos Tavern",
#   location: [ 123.123123, -82.1231231 ],
#   description: "Bacon Ipsum salty grease fat pork steak",
#   episode: {
#     number: 11,
#     season: 3
#     name: "Classics"
#   }
# }

type Restaurant {
  name: String!
  location: [Float!] # [lng, lat]
  description: String
  rating: Float
  season: Int!
}

type Query {
  allRestaurants: [Restaurant!],
}